# Generated by Django 3.2.6 on 2022-06-15 11:00

import datetime
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Sensor',
            fields=[
                ('address', models.CharField(max_length=200, primary_key=True, serialize=False)),
                ('name', models.CharField(max_length=1000)),
                ('is_group', models.BooleanField(default=False)),
                ('status', models.IntegerField(default=0)),
                ('created_at', models.DateField(default=datetime.date.today)),
                ('updated_at', models.DateField()),
            ],
        ),
        migrations.CreateModel(
            name='SensorLabel',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('address', models.CharField(max_length=200)),
                ('name', models.CharField(max_length=1000)),
                ('chart_type', models.CharField(max_length=100)),
                ('sensor_address', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='home.sensor')),
            ],
        ),
    ]
