# Generated by Django 3.2.6 on 2022-06-20 02:23

import datetime
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('home', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='SensorRequest',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('address', models.CharField(max_length=1000)),
                ('chart_type', models.CharField(max_length=100)),
            ],
        ),
        migrations.AlterField(
            model_name='sensor',
            name='updated_at',
            field=models.DateField(default=datetime.date.today),
        ),
    ]
