# Generated by Django 3.2.6 on 2022-06-26 15:28

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('apps', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='sensorrequest',
            name='label',
            field=models.CharField(default='test', max_length=1000),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='sensorrequest',
            name='sensor_name',
            field=models.CharField(default='test', max_length=1000),
            preserve_default=False,
        ),
    ]
