# Generated by Django 3.2.6 on 2022-06-26 15:54

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('apps', '0002_auto_20220626_2228'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='sensorrequest',
            name='address',
        ),
        migrations.RemoveField(
            model_name='sensorrequest',
            name='label',
        ),
        migrations.RemoveField(
            model_name='sensorrequest',
            name='sensor_name',
        ),
        migrations.AddField(
            model_name='sensorrequest',
            name='label_address',
            field=models.ForeignKey(default=0, on_delete=django.db.models.deletion.CASCADE, to='apps.sensorlabel'),
        ),
        migrations.AddField(
            model_name='sensorrequest',
            name='sensor_address',
            field=models.ForeignKey(default=0, on_delete=django.db.models.deletion.CASCADE, to='apps.sensor'),
        ),
    ]
