# Generated by Django 3.2.6 on 2022-07-03 06:40

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('apps', '0006_rename_is_relay_sensor_is_monitor'),
    ]

    operations = [
        migrations.AddField(
            model_name='sensor',
            name='address_off',
            field=models.CharField(default='', max_length=200),
        ),
    ]
