# Generated by Django 3.2.6 on 2022-07-04 09:09

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('apps', '0007_sensor_address_off'),
    ]

    operations = [
        migrations.CreateModel(
            name='CronJob',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('address', models.CharField(max_length=100)),
                ('name', models.CharField(max_length=100)),
                ('condition', models.CharField(max_length=100)),
                ('sensor_address', models.ForeignKey(default=0, on_delete=django.db.models.deletion.CASCADE, to='apps.sensor')),
            ],
        ),
    ]
