# Generated by Django 3.2.6 on 2022-07-15 17:29

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('apps', '0008_cronjob'),
    ]

    operations = [
        migrations.DeleteModel(
            name='CronJob',
        ),
    ]
